from tkinter import *

def click(event):
    global e
    text=event.widget.cget("text")
    #print(text)
    if text=="=":
        if e.get().isdigit():
            value=int(e.get())
        else:
            try:
                value=eval(e.get())
            except Exception:
                value="ERROR"
        e.set(value)
        entry.update()
    elif text=="CR":
        e.set("")
        entry.update()
    else:
        e.set(e.get()+text)
        entry.update()
root=Tk()
root.title("CALCULATOR BY RAJESH")
root.config(background="grey")
root.geometry("400x500")
root.minsize(400,500)
e=StringVar()
entry=Entry(root,textvariable=e,font="Verdana 25 bold",relief=SUNKEN)
entry.pack(side=TOP,ipadx=8,pady=20,padx=10,fill=X)

f=Frame(root)
b1=Button(f,text="9",font="lucida 33 bold",padx=10)
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
b1=Button(f,text="8",font="lucida 32 bold",padx=10)
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
b1=Button(f,text="7",font="lucida 32 bold",padx=10)
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
b1=Button(f,text="CR",font="lucida 30 bold")
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
f.pack()

f=Frame(root)
b1=Button(f,text="6",font="lucida 34 bold",padx=10)
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
b1=Button(f,text="5",font="lucida 33 bold",padx=10)
b1.pack(side=LEFT,padx=3)
b1.bind("<Button-1>",click)
b1=Button(f,text="4",font="lucida 33 bold",padx=10)
b1.pack(side=LEFT,padx=3)
b1.bind("<Button-1>",click)
b1=Button(f,text=" / ",font="lucida 34 bold")
b1.pack(side=LEFT,padx=3)
b1.bind("<Button-1>",click)
f.pack()

f=Frame(root)
b1=Button(f,text="3",font="lucida 33 bold",padx=10)
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
b1=Button(f,text="2",font="lucida 33 bold",padx=10)
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
b1=Button(f,text="1",font="lucida 33 bold",padx=10)
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
b1=Button(f,text=" * ",font="lucida 33 bold")
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
f.pack()

f=Frame(root)
b1=Button(f,text="0",font="lucida 30 bold",padx=10)
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
b1=Button(f,text=".",font="lucida 28 bold",padx=10)
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
b1=Button(f,text="+",font="lucida 28 bold",padx=10)
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
b1=Button(f,text="-",font="lucida 28 bold",padx=10)
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
b1=Button(f,text="=",font="lucida 30 bold")
b1.pack(side=LEFT,padx=3,pady=3)
b1.bind("<Button-1>",click)
f.pack()
root.mainloop()
